language: java

jdk:
  - oraclejdk7

# script will call assemble
install: true

before_install:
  - chmod +x gradlew

script:
  - export GRADLE_OPTS=-Xmx1024m
  - ./gradlew assemble --stacktrace
  - ./gradlew check jacocoFullReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
 
 # cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
